### ISSUE TITLE
My IP is reported as listed on malc0de even though it isn't

### ISSUE THREAD

**Issue by moebiuseye** [jgamblin/isthisipbad#14]
I ran the script against my IP and the script reported (in red)

```
xx.xx.110.155 is listed on malc0de
```

When checking the list @ http://malc0de.com/bl/IP_Blacklist.txt , I couldn't find that IP.

**Comment by smmr0** [comment]
See https://github.com/jgamblin/badactors/issues/2

**Comment by jgamblin** [comment]
Guys,  I havent had time to look at this repo in a long time.  I will try to get to it as soon as possible but this was written for a one time purpose and I have not used it in a while.
