### ISSUE TITLE
SyntaxError: invalid syntax--On Line number 61

### ISSUE THREAD

**Issue by harishpal2090** [jgamblin/isthisipbad#19]
$ python --version
Python 3.6.4 :: Anaconda, Inc.
==================================== 
 File "<ipython-input-4-8d0e67e6f302>", line 61
    html_content = opened_request.read()
               ^
SyntaxError: invalid syntax

**Comment by altmas5** [comment]
The current version do not support python3.
However, there is a pull request to make it compatible with python3 #20
