### ISSUE TITLE
About removing UceProtect

### ISSUE THREAD

**Issue by istiak101** [jgamblin/isthisipbad#22]
Will you please remove UceProtect as they are not trusted?

Reference:

https://blog.sucuri.net/2021/02/uceprotect-when-rbls-go-bad.html

https://www.linode.com/community/questions/2324/uceprotectnet-has-us-blacklisted

https://www.titanhq.com/blog/warning-ignore-pay-for-de-listing-blacklist-service/

https://community.spiceworks.com/topic/2170592-uceprotect-blacklist-scam

https://wordtothewise.com/2018/05/uceprotect-gdpr-fallout/

http://kontech.net/uceprotect-blacklist-scheme-2020/

https://twitter.com/search?q=uceprotect

https://www.lowendtalk.com/discussion/comment/3204705

**Comment by jgamblin** [comment]
@istiak101 thanks, I had not updated this code in a long time.  I removed these sources and took the opportunity to port this to python3.
