### ISSUE TITLE
There isn't a license file

### ISSUE THREAD

**Issue by unixorn** [jgamblin/isthisipbad#3]
What's the license for this code?

**Comment by jgamblin** [comment]
What license should I use for the "I hacked this together at a Starbucks and I don't care what you do with it as long as I am not somehow responsible?"  Seriously.. I don't know enough about the different license models to pick.

**Comment by jgamblin** [comment]
Added MIT License after talking to a friend.  Hope that works for you.

**Comment by unixorn** [comment]
MIT license is great, thanks. It just makes it easier to use things at work when there's a license.
