### ISSUE TITLE
create a main() method

### ISSUE THREAD

**Issue by jabbalaci** [jgamblin/isthisipbad#6]
Nice script. However, the code below 

```
if __name__ == "__main__":
```

is too long. It would look much better if you called a method and you put everything in there:

```
if __name__ == "__main__":
    main()
```

You can also split up the `main()` method to smaller functions/methods.

**Comment by jgamblin** [comment]
Thanks! I am really new to python and seriously dont know what I am doing.  i will take some time this weekend to look through a style guide and see if I cant clean it up.

**Comment by jabbalaci** [comment]
What took 6 years?
